[package]
name = "jsp"
version = "0.1.0"
edition = "2024"
description = "Modular and efficient language processor for a subset of Javascript"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
